#ifndef __RPC_SERVER_HANDSET_H
#define __RPC_SERVER_HANDSET_H

#define HEADPHONE_SW_IO				0xA3

/* IOCTLs for headphone sw */
#define HEADPHONE_SW_IOCTL_DETECT_START		_IO(HEADPHONE_SW_IO, 0x01)
#define HEADPHONE_SW_IOCTL_DETECT_STOP		_IO(HEADPHONE_SW_IO, 0x02)

#endif
